name: CI
on:
  push:
  workflow_dispatch:
  schedule:
    - cron: "1 1 * * 1"
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: gradle runReleaseExecutableNative
